### ISSUE TITLE
Serve error with Angular 6

### ISSUE THREAD

**Issue by pw17l008** [codehandbook/angular-leaflet#1]
Hi there! 

So i downloaded you repo and wanted to serve it like I would with Angular but am getting the following errors!

Could not find module "@angular-devkit/build-angular" from "/Users/username/Downloads/angular-leaflet-master".
Error: Could not find module "@angular-devkit/build-angular" from "/Users/username/Downloads/angular-leaflet-master".
    at Object.resolve (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable._trySubscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:29:22)
    at DoOperator.call (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:29:23)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:24:22)
    at /usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:72:14)

your help is much appreciated! Thank you!

Konstantin

**Comment by rediaz2109** [comment]
Hello, I downloaded and start this app and it works correctly. Now I saw a kind of map in the UI. 
I recommend you to delete your node_modules directory and download again, in my case I used the version 8.11 of node and npm for downloaded the packages (other people use Yarn).

**Comment by codehandbook** [comment]
> Hi there!
> 
> So i downloaded you repo and wanted to serve it like I would with Angular but am getting the following errors!
> 
> Could not find module "@angular-devkit/build-angular" from "/Users/username/Downloads/angular-leaflet-master".
> Error: Could not find module "@angular-devkit/build-angular" from "/Users/username/Downloads/angular-leaflet-master".
> at Object.resolve (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
> at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
> at Observable._trySubscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:43:25)
> at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:29:22)
> at DoOperator.call (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:29:23)
> at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:24:22)
> at /usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
> at Object.subscribeToResult (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
> at MergeMapSubscriber._innerSub (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
> at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
> 
> your help is much appreciated! Thank you!
> 
> Konstantin

Hey @pw17l008 a quick google search took me to a [stackoverflow solution](https://stackoverflow.com/questions/50333003/could-not-find-module-angular-devkit-build-angular). Do have a look and let me know if it helps. Thanks !
